config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    member do
      get 'basket', to: 'users#basket'
    end

    resources :orders, only: %i[index show create]
  end
  resources :ebooks
  resources :categories
  resources :orders

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'add_to_basket/:id', to: 'ebooks#add_to_basket'
  delete 'remove_from_basket/:id', to: 'ebooks#remove_from_basket'
  root to: 'ebooks#index'
end

app/views/shared/_ebooks.html.erb
<% ebooks.each.with_index do |ebook, i| %>
  <% if i%3 == 0 %>
    <div class="row">
  <% end %>
  <div class="col-sm-4 justify-content-center">
    <div class="card">
      <%= image_tag ebook.photo_url, class: 'card-img-top', alt: "#{ebook.title} cover", height: '250px'%>
      <div class="card-body">
        <h5 class="card-title"><%= link_to ebook.title, ebook_path(ebook) %></h5>
        <h6 class="card-title"><strong><%= ebook.author %></strong></h6>
        <p class="card-text"><small class="badge badge-secondary"><%= link_to ebook.category.name, category_path(ebook.category) %></small></p>
        <p class="card-text"><%= "#{ebook.price} zł" %></p>
        <p><small>Available: <%= ebook.stock %></small></p>
        <% if logged_in? && !current_user.admin? %>
          <div class="card-text"><%= link_to 'Add to basket', "/add_to_basket/#{ebook.id}", class: 'btn btn-sm btn-primary' %></div>
        <% elsif logged_in? && current_user.admin? %>
          <div class="card-text">
            <div class="row">
              <div class="col"><%= link_to 'Edit Item', edit_ebook_path(ebook), class: 'btn btn-sm btn-primary' %></div>
              <div class="col"><%= link_to 'Delete Item', ebook_path(ebook), method: :delete, class: 'btn btn-sm btn-danger' %></div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <% if i%3 == 2 || i == (ebooks.to_ary.size - 1) %>
    </div>
  <% end %>
<% end %>
<%= will_paginate(ebooks, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer, class: 'justify-content-center') %>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <%= link_to 'BookShelf', root_path, class:'navbar-brand'%>
    <ul class="navbar-nav mt-2 mt-lg-0">
      <% if logged_in? && current_user.admin?%>
        <li class="nav-item">
          <%= link_to 'Add Product', new_ebook_path, class: 'nav-link'%>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Categories Actions
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Add Ebooks Category', new_category_path, class: 'dropdown-item'%>
            <%= link_to 'Categories List', categories_path, class: 'dropdown-item'%>
          </div>
        </li>
      <% end %>
    </ul>
    <%= form_with url: request.original_url, method: :get, local: true, class: 'form-inline ebook-search-form mr-auto' do |f| %>
      <%= f.text_field :search_query, placeholder: "Search#{search_placeholder}", class:'form-control mr-sm-2'%>
      <%= f.submit 'Search', class: 'btn btn-outline-primary my-2 my-sm-0'%>
    <% end %>
    <ul class="navbar-nav mt-2 mt-lg-0">
      <% unless logged_in? %>
        <li class="nav-item">
          <%= link_to 'Sign up', new_user_path, class: 'nav-link'%>
        </li>
        <li class="nav-item">
          <%= link_to 'Login', login_path, class: 'nav-link'%>
        </li>
      <% else %>
        <% unless current_user.admin? %>
          <li>
            <%= link_to (fa_icon "shopping-basket", class: 'fa-2x'), basket_user_path(current_user), class: 'nav-link'%>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Your Profile
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to 'Edit Profile', edit_user_path(current_user), class: 'dropdown-item'%>
              <%= link_to 'Your Orders', user_orders_path(current_user), class: 'dropdown-item'%>
            </div>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to 'Logout', logout_path, method: :delete, class: 'nav-link btn btn-secondary'%>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/shared/_save_errors.erb
<% if model.errors.present? %>
  <div class ="row">
    <div class="col-sm-10 offset-sm-2">
      <div class="alert alert-success">
          <h2>
            <%= pluralize(model.errors.count, 'error') %>
              prohibited this <%= model.class.name.downcase %> from being saved:
          </h2>
            <ul>
              <% model.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_sidenav.html.erb
<div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
  <div class="side-nav-option"><%= link_to 'All Categories', ebooks_path, class:'nav-link' %></div>
  <% @categories.each do |c| %>
    <div class="side-nav-option"><%= link_to c.name, category_path(c), class:'nav-link' %></div>
  <% end %>
</div>