config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    member do
      get 'basket', to: 'users#basket'
    end

    resources :orders, only: %i[index show create]
  end
  resources :ebooks
  resources :categories
  resources :orders

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'add_to_basket/:id', to: 'ebooks#add_to_basket'
  delete 'remove_from_basket/:id', to: 'ebooks#remove_from_basket'
  root to: 'ebooks#index'
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, uniqueness: true

  has_many :ebooks
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: %i[show]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to root_path, notice: 'Category Created'
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to root_path, notice: 'Category updated'
    else
      render 'new'
    end
  end

  def show
    @categories = Category.all
    @category = Category.find(params[:id])
    @ebooks = EbooksSearch.new(query_params(@category.id).merge(page: params[:page], per_page: params[:per_page])).call
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.destroy
      redirect_to root_path, notice: 'Category deleted'
    else
      redirect_to root_path, notice: 'There was a problem removing category'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def query_params(category_id)
    p = params.permit(:search_query)
    { search_query: p[:search_query], category: category_id }.compact
  end
end

app/views/categories/_form.html.erb
<%= render 'shared/save_errors', model: category%>

<div class="card bg-dark text-light form-card">
  <div class="col-sm-12">
    <%= form_for(category, html: { class: 'form-hotizontal', role: 'form' }) do |f| %>
      <div class="form-group row">
          <strong class="col-sm-2 col-form-label"><%= f.label :name %></strong>
        <div class="col-sm-10 centered-element">
          <%= f.text_field :name, class: 'form-control', placeholder: 'Category name', autofocus: true %>
        </div>
      </div>
      <div class="form-group row">
        <div class="offset-sm-2 col-sm-10">
          <%= f.submit(category.new_record? ? 'Create Category' : 'Update Category', class: 'btn btn-primary')%>
          <%= link_to 'Back', root_path, class: 'btn btn-secondary'%>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/edit.html.erb
<h1 align="center" >Edit Category</h1>

<%= render 'form', category: @category %>

app/views/categories/index.html.erb
<div class="categories-list">
  <% @categories.each do |c| %>
      <div class="card">
        <div class="card-body">
            <div class="row my-auto">
              <div class="col my-auto">
                <%= link_to c.name, category_path(c)%>
              </div>
              <div class="col">
                <div class="row justify-content-end">
                  <div class="action-link">
                    <%= link_to 'Edit Category', edit_category_path(c), class: 'btn btn-primary' %>
                  </div>
                  <div class="action-link">
                    <%= link_to 'Delete Category', category_path(c), method: :delete, class: 'btn btn-danger' %>
                  </div>
                </div>
              </div>
            </div>
        </div>
      </div>
  <% end %>
</div>

app/views/categories/new.html.erb
<h1 align="center" >Create Category</h1>

<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<h1 align="center">Ebooks of Category <%= @category.name%></h1>

<%= render 'shared/ebooks', ebooks: @ebooks %>